### ISSUE TITLE
parser fails to parse big traces

### ISSUE THREAD

**Issue by Da5hes** [shankarapailoor/trace2syz#1]
after tracing some progs and trying to parse them with trace2syz, the parses fails
in one case it fails with:
"Failed to eval flag: SNDCTL_TMR_STOP"
in other case it fails with:
 "Cannot evaluate flags with more than one element"

the first case is a trace of nano editing a file
the second case is tracing syz-manager

trying with other big progs causes other errors about flags eval

**Comment by shankarapailoor** [comment]
Hi @Da5hes!

Thanks for letting me know. I believe both have been fixed and let me know if you see more errors. In general if you see "Failed to eval flag: ```SNDCTL_TMR_STOP```" it means that this is a flag which is not recognized by Syzkaller. I have been maintaining a separate in-memory map [here](https://github.com/shankarapailoor/trace2syz/blob/master/utils/util.go#L48)  which maps these cases to their corresponding values. I plan on creating a PR to Syzkaller maintainers to add these constants to their grammar so that I don't need this additional mapping. 

If you encounter any other issues try running the tool with  -v [loglevel] flag to get more debug info. E.g.,

```./bin/trace2syz -v 1 -file somefile```

You get more debug output the larger the loglevel.

**Comment by Da5hes** [comment]
#2 fixed the problem with the currently traced applications

**Comment by shankarapailoor** [comment]
Thanks @Da5hes. Can I close this?

**Comment by Da5hes** [comment]
just one more thing
i encountered a further problem, parsing a network related trace and getting:
2018/10/11 13:45:05 Parsing Arg of syz type: int16be, ir type: Field Type
2018/10/11 13:45:05 Parsing Arg of syz type: int16be, ir type: Call Type
2018/10/11 13:45:05 Parsing Arg of syz type: int32be, ir type: Field Type
2018/10/11 13:45:05 Parsing Arg of syz type: int32be, ir type: Call Type
2018/10/11 13:45:05 Parsing ip address for non-union type int32be

**Comment by shankarapailoor** [comment]
Could you send me the trace so I can take a look? In theory I could just handle the case where the syzkaller type is an int, but I always thought the ip address would be a union type. I want to make sure there isn't some hidden issue.

**Comment by Da5hes** [comment]
rename to .xz
[nmaptrace.zip](https://github.com/shankarapailoor/trace2syz/files/2468737/nmaptrace.zip)

**Comment by shankarapailoor** [comment]
I see the issue and I will put in a fix tonight. Thanks again!
